# Generated by Django 3.0.5 on 2020-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_auto_20200411_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
