# Generated by Django 3.0.5 on 2020-04-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_auto_20200411_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='promo_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
