# Generated by Django 3.0.5 on 2020-04-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_auto_20200411_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyOutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sum', models.IntegerField()),
                ('status', models.TextField(default='processing')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tg_bot.Profile')),
            ],
        ),
    ]
