# Generated by Django 3.0.5 on 2020-04-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_moneyinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
