# Generated by Django 3.0.5 on 2020-04-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_auto_20200412_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
