# Generated by Django 3.0.5 on 2020-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0010_auto_20200412_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='photo_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
