# Generated by Django 3.0.5 on 2020-04-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_message_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='tg_bot.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='chat',
        ),
        migrations.AddField(
            model_name='order',
            name='documents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='photos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FreelanceApplication',
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='tg_bot.Order'),
        ),
    ]
