# Generated by Django 3.0.5 on 2020-04-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_auto_20200413_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plagiarism',
            field=models.TextField(blank=True, null=True),
        ),
    ]
