# Generated by Django 3.0.5 on 2020-04-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0013_order_plagiarism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='documents',
            new_name='files',
        ),
        migrations.RemoveField(
            model_name='order',
            name='photos',
        ),
    ]
