# Generated by Django 3.0.5 on 2020-04-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0014_auto_20200413_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
