# Generated by Django 3.0.5 on 2020-04-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0016_auto_20200413_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyoutrequest',
            name='requisites',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
