# Generated by Django 3.0.5 on 2020-04-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0017_moneyoutrequest_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
